clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
install:
  - npm install
test_script:
  - node --version && npm --version
  - cmd: npm test
build: off
